name: CI Pipeline

on: [push]

jobs:

  validar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validar codigo
        run: echo Codigo validado

  build:
    runs-on: ubuntu-latest
    needs: validar
    steps:
      - uses: actions/checkout@v4
      - name: Simular build
        run: echo Build executado

  segredo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Mostrar segredo
        run: echo Mensagem secreta ${{ secrets.MENSAGEM_SECRETA }}